package com.timecraft.timecraft.service;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Value;

import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.timecraft.timecraft.model.Schedule;

import lombok.extern.slf4j.Slf4j;

/**
 * Ollama LLM advisor for TimeCraft.
 *
 * Calls Ollama directly via its REST API using WebClient.
 * No Spring AI dependency required.
 *
 * IMPORTANT: This service is purely advisory.
 * It NEVER generates, modifies, or validates schedules.
 * All hard constraint enforcement stays in SchedulingEngine.java.
 */
@Slf4j
@Service
public class OllamaScheduleAdvisorService {

    private final RestClient restClient;
    private final ObjectMapper objectMapper;

    @Value("${ollama.base-url:http://localhost:11434}")
    private String ollamaBaseUrl;

    @Value("${ollama.model:llama3.2}")
    private String ollamaModel;

    public OllamaScheduleAdvisorService(ObjectMapper objectMapper) {
        this.restClient  = RestClient.create();
        this.objectMapper = objectMapper;
    }

    // ── 1. Summarize full schedule after generation ───────────────────────────

    public String summarizeSchedule(List<Schedule> schedules,
            Object semester, String schoolYear) {

        String scheduleText = buildScheduleText(schedules);

        String prompt = """
                You are a college scheduling assistant for TimeCraft.
                Below is a finalized, conflict-free timetable for %s %s,
                generated by the constraint-solving engine.

                %s

                Your tasks:
                1. Write a short plain-language summary of this schedule
                   for the program head (2-3 paragraphs max).
                2. Flag any SOFT concerns only, for example:
                   - A teacher with 4 or more subjects assigned
                   - Any subject scheduled at an unusual time
                   - Sections that appear overloaded
                3. DO NOT modify, rearrange, or suggest rescheduling.
                4. DO NOT invent subjects, rooms, or teachers not listed above.
                5. Keep your response concise and professional.
                """.formatted(semester.toString(), schoolYear, scheduleText);

        return call(prompt);
    }

    // ── 2. Explain generation result (counts summary) ────────────────────────

    public String explainGenerationResult(int successful, int conflicted,
            String semester, String schoolYear) {

        String prompt = """
                You are a scheduling assistant. A timetable was just generated
                for %s %s with the following results:
                - Successfully scheduled: %d subjects
                - Conflicts (unresolved): %d subjects

                Write 2-3 sentences explaining this result to a program head
                in plain, non-technical language.
                If there are conflicts, briefly note they need manual review.
                Do not list specific subjects. Be concise and professional.
                """.formatted(semester, schoolYear, successful, conflicted);

        return call(prompt);
    }

    // ── 3. Answer a natural language query about the schedule ─────────────────

    public String answerQuery(String question, List<Schedule> schedules) {

        String scheduleText = buildScheduleText(schedules);

        String prompt = """
                You are a scheduling assistant for a college timetable system.
                Use ONLY the schedule data below to answer the question.
                If the answer is not in the data, say:
                "I don't have enough information to answer that."

                Schedule data:
                %s

                Question: %s

                Answer concisely and factually. Do not guess.
                """.formatted(scheduleText, question);

        return call(prompt);
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private String buildScheduleText(List<Schedule> schedules) {
        if (schedules == null || schedules.isEmpty()) {
            return "(No schedule data available)";
        }

        return schedules.stream()
                .map(s -> {
                    String teacher = s.getTeacher() != null
                            ? s.getTeacher().getFullName() : "TBA";
                    String room = s.getRoom() != null
                            ? s.getRoom().getRoomNumber() : "TBA";
                    String ts1 = s.getTimeslot() != null
                            ? s.getTimeslot().getLabel() : "TBA";
                    String ts2 = s.getTimeslot2() != null
                            ? s.getTimeslot2().getLabel() : "";
                    String section = s.getSection() != null
                            ? s.getSection().getDisplayLabel() : "TBA";

                    return String.format(
                            "- [%s] %s | Teacher: %s | Room: %s | Time: %s %s | Section: %s",
                            s.getSubject().getCode(),
                            s.getSubject().getName(),
                            teacher, room, ts1, ts2, section);
                })
                .collect(Collectors.joining("\n"));
    }

    /**
     * Calls Ollama REST API directly.
     * POST http://localhost:11434/api/generate
     */
    private String call(String promptText) {
        log.debug("Sending prompt to Ollama ({} chars)", promptText.length());

        try {
            Map<String, Object> requestBody = Map.of(
                    "model",  ollamaModel,
                    "prompt", promptText,
                    "stream", false);

            Map<?, ?> response = restClient.post()
                    .uri(ollamaBaseUrl + "/api/generate")
                    .header("Content-Type", "application/json")
                    .body(requestBody)
                    .retrieve()
                    .body(Map.class);

            if (response != null && response.containsKey("response")) {
                String result = response.get("response").toString();
                log.debug("Ollama responded ({} chars)", result.length());
                return result;
            }

            return "AI summary unavailable.";

        } catch (Exception e) {
            log.warn("Ollama call failed: {}", e.getMessage());
            return "AI summary unavailable.";
        }
    }
}