ALTER TABLE schedules ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);
ALTER TABLE curricula ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE curricula ADD COLUMN IF NOT EXISTS deleted_by VARCHAR(255);